[project]
name = "spectrum_instruments"
version = "0.1.0"
authors = [
    { name = "Bodo Kaiser", email = "bodo.kaiser@physik.uni-muenchen.de" }
]
dependencies = [
    "spcm==1.9.1",
    "numpy==2.0.2",
    "scipy==1.13.1",
    "sipyco @ git+https://github.com/m-labs/sipyco.git@v1.9"
]